// Comprehensive list of board game mechanics
// Based on BoardGameGeek's mechanic categories and common game mechanics

export const BOARD_GAME_MECHANICS = [
  // Action/Movement
  "Action Points",
  "Action Drafting", 
  "Action Queue",
  "Action Retrieval",
  "Area Movement",
  "Grid Movement",
  "Hexagon Grid",
  "Line of Sight",
  "Map Addition",
  "Map Deformation",
  "Modular Board",
  "Movement Points",
  "Network and Route Building",
  "Point to Point Movement",
  "Race",
  "Roll and Move",
  "Semi-Cooperative Game",
  "Simultaneous Action Selection",
  "Speed Matching",
  "Time Track",
  "Turn Order: Auction",
  "Turn Order: Claim Action",
  "Turn Order: Pass Order",
  "Turn Order: Progressive",
  "Turn Order: Random",
  "Turn Order: Role Order",
  "Turn Order: Stat-Based",
  "Variable Turn Order",

  // Area Control & Territory
  "Area Control / Area Influence",
  "Area Enclosure",
  "Area Majority / Influence",
  "Area-Impulse",
  "Chit-Pull System",
  "Enclosure",
  "King of the Hill",
  "Territory Building",
  "Tug of War",
  "Zone of Control",

  // Auction & Bidding
  "Auction/Bidding",
  "Auction: Dutch",
  "Auction: English",
  "Auction: Fixed Placement",
  "Auction: Multiple Lot",
  "Auction: Once Around",
  "Auction: Sealed Bid",
  "Auction: Turn Order Until Pass",
  "Bidding Pool",

  // Card Mechanics
  "Card Drafting",
  "Card Play Conflict Resolution",
  "Deck Building",
  "Deck Construction",
  "Hand Management",
  "Ladder Climbing",
  "Melding and Splaying",
  "Multi-Use Cards",
  "Open Drafting",
  "Passed Action Token",
  "Programmed Movement",
  "Simultaneous Action Selection",
  "Tableau Building",
  "Take That",
  "Trick-taking",

  // Collection & Set Building
  "Collection",
  "Commodity Speculation",
  "Contracts",
  "End Game Bonuses",
  "Highest-Lowest Scoring",
  "Hot Potato",
  "Income",
  "Investment",
  "Market",
  "Matching",
  "Pattern Building",
  "Pattern Recognition",
  "Set Collection",
  "Stock Holding",
  "Tags",
  "Tile Placement",
  "Victory Points as a Resource",

  // Combat & Conflict
  "Area Control / Area Influence",
  "Battle Card Driven",
  "Campaign / Battle Card Driven",
  "Capture / Eliminate",
  "Combat Results Table",
  "Dice Rolling",
  "Events",
  "Hex-and-Counter",
  "Hidden Roles",
  "Player Elimination",
  "Rock-Paper-Scissors",
  "Secret Unit Deployment",
  "Simulation",
  "Variable Player Powers",
  "Wargame",

  // Cooperation
  "Cooperative Game",
  "Semi-Cooperative Game",
  "Team-Based Game",
  "Traitor Game",

  // Deduction & Hidden Information
  "Deduction",
  "Events",
  "Follow",
  "Hidden Information",
  "Hidden Movement",
  "Hidden Roles",
  "Legacy Game",
  "Memory",
  "Predictive Bid",
  "Secret Unit Deployment",
  "Semi-Hidden Information",
  "Storytelling",
  "Traitor Game",
  "Variable Setup",

  // Dice & Randomness
  "Dice Rolling",
  "Push Your Luck",
  "Re-rolling and Locking",
  "Dice Worker Placement",

  // Drafting
  "Card Drafting",
  "Open Drafting",
  "Action Drafting",

  // Economic & Trading
  "Commodity Speculation",
  "Contracts",
  "Investment",
  "Market",
  "Negotiation",
  "Stock Holding",
  "Trading",
  "Valuation",

  // Engine Building & Production
  "Automatic Resource Growth",
  "Conversion",
  "Engine Building",
  "Income",
  "Interrupts",
  "Layering",
  "Loans",
  "Maintenance",
  "Market",
  "Production",
  "Resource to Move",
  "Track Movement",
  "Variable Set-up",

  // Tile & Pattern Placement
  "Abstract Strategy",
  "Connections",
  "Enclosure",
  "Grid Coverage",
  "Hexagon Grid",
  "Line Drawing",
  "Map Addition",
  "Modular Board",
  "Network and Route Building",
  "Paper-and-Pencil",
  "Pattern Building",
  "Pattern Recognition",
  "Polyomino Placement",
  "Square Grid",
  "Tile Placement",

  // Worker Placement & Role Selection
  "Action Drafting",
  "Action Points",
  "Action Queue",
  "Dice Worker Placement",
  "Passed Action Token",
  "Role Selection",
  "Rondel",
  "Solo / Solitaire Game",
  "Turn Order: Claim Action",
  "Variable Phase Order",
  "Worker Placement",
  "Worker Placement with Dice Workers",
  "Worker Placement, Different Worker Types",

  // Other Popular Mechanics
  "Bingo",
  "Bluffing",
  "Chaining",
  "Communication Limits",
  "Connections",
  "Cooperative Game",
  "Crayon Rails",
  "Crokinole",
  "Dexterity",
  "Elapsed Real Time",
  "Flicking",
  "Grid Coverage",
  "I Cut, You Choose",
  "Impulse Movement",
  "Induction",
  "Legacy Game",
  "Line Drawing",
  "Lose a Turn",
  "Mancala",
  "Miniatures",
  "Move Through Deck",
  "Multiple Maps",
  "Once-Per-Game Abilities",
  "Ordering",
  "Package Delivery",
  "Paper-and-Pencil",
  "Partnerships",
  "Physical Removal",
  "Pick-up and Deliver",
  "Pieces as Map",
  "Player Judge",
  "Prisoner's Dilemma",
  "Programmed Movement",
  "Real-Time",
  "Relative Movement",
  "Roles with Asymmetric Information",
  "Route/Network Building",
  "Scenario / Mission / Campaign Game",
  "Score-and-Reset Game",
  "Slide/Push",
  "Solo / Solitaire Game",
  "Spelling",
  "Stacking and Balancing",
  "Static Capture",
  "Sudden Death Ending",
  "Supply Chain Management",
  "Tech Trees / Tech Tracks",
  "Three Dimensional Movement",
  "Throw It In Your Cart",
  "Voting",
  "Win / Lose / Banana"
].sort();

// Most commonly used mechanics (for quick access or separate display)
export const POPULAR_MECHANICS = [
  "Area Control / Area Influence",
  "Auction/Bidding", 
  "Card Drafting",
  "Deck Building",
  "Dice Rolling",
  "Engine Building",
  "Hand Management",
  "Pattern Building",
  "Push Your Luck",
  "Role Selection",
  "Set Collection",
  "Tableau Building",
  "Tile Placement",
  "Variable Player Powers",
  "Worker Placement"
].sort();
