// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcuknlhpfqlidbjfegra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdWtubGhwZnFsaWRiamZlZ3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTI5NTAsImV4cCI6MjA2ODY2ODk1MH0.rWo-wX8xw7Gd-I4VYaCTXMDWLtbupcJR_mMlaIC8cIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});